### ISSUE TITLE
Investigate whether Xamarin.Forms can be converted to .NET Standard (2.0)

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1122]
@alexfdezsauco , please investigate whether we can already convert it.

**Comment by alexfdezsauco** [comment]
Yes, I will, I'm already use Catel Core as rereference in a XF project

**Comment by GeertvanHorrik** [comment]
As discussed, moving to 5.3

**Comment by ChristophSchmidpeter** [comment]
To get Catel.MVVM.Xamarin.Forms to compile, I had to add 0x801318F3 to the project's VerifyIgnoreCodes in Weavers.xml. (as it has already been done in the Catel.MVVM.UWP project)

**Comment by ChristophSchmidpeter** [comment]
I get a starup exception (UWP not Android):
InnerException {System.TypeInitializationException: The type initializer for '<Module>' threw an exception.

 ---> System.PlatformNotSupportedException: Retrieving information about local processes is not supported on this platform.
at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
at System.Diagnostics.ProcessManager.GetProcessInfo(Int32 processId, String machineName)
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.get_ProcessName()
at Catel.EnvironmentHelper.IsHostedByProcess(String processName, Boolean supportParentProcesses)
at Catel.EnvironmentHelper.IsProcessCurrentlyHostedByVisualStudio(Boolean checkParentProcesses)
at Catel.EnvironmentHelper.IsProcessCurrentlyHostedByTool(Boolean checkParentProcesses)
at Catel.IoC.ServiceLocatorAutoRegistrationManager..ctor(IServiceLocator serviceLocator)
at Catel.IoC.ServiceLocator..ctor()
at Catel.IoC.IoCFactory.<>c.<.cctor>b__6_0()
at Catel.IoC.IoCFactory.CreateServiceLocator(Boolean initializeServiceLocator)
at Catel.IoC.IoCConfiguration.UpdateDefaultComponents()
at Catel.IoC.IoCConfiguration.get_DefaultServiceLocator()
at Catel.IoC.ServiceLocator.get_Default()
at Catel.Core.ModuleInitializer.Initialize()
at .cctor()
--- End of inner exception stack trace ---
at Catel.MVVM.ModuleInitializer.Initialize()
at .cctor()} System.Exception {System.TypeInitializationException}

As workaround I had to ‘return false;’ in IsProcessCurrentlyHostedByVisualStudio, IsProcessCurrentlyHostedByExpressionBlend, and IsProcessCurrentlyHostedBySharpDevelop

**Comment by ChristophSchmidpeter** [comment]
As I understand is that for UWP projects with Xamarin.Forms the project Catel.MVVM.Xamarin.Forms is required, without Catel.MVVM.UWP. How can the right NuGet package for the UWP project be selected by the user, depending on the use case? (NuGet allows you normally just to select the installation version)

**Comment by alexfdezsauco** [comment]
We started a new approach to support XF via NS20. You can compile by your self the feature branch https://github.com/Catel/Catel/tree/feature/1122. The NuGet is not available yet. We are working in a demo app in order to find the missing features. I will push it soon in the XF demo app repository https://github.com/Catel/Catel.Examples.Xamarin.Forms

**Comment by alexfdezsauco** [comment]
There is an available implementation for NS for the methods IsProcessCurrentlyHostedByVisualStudio, IsProcessCurrentlyHostedByExpressionBlend, and IsProcessCurrentlyHostedBySharpDevelop

**Comment by alexfdezsauco** [comment]
Pushed Master-Detail example app, but at this point requires the Catel sources from feature/1122 branch.  No package available yet.
