### ISSUE TITLE
Error Implementing IDataWindow with RadWindow

### ISSUE THREAD

**Issue by halbustami** [Catel/Catel#1125]
I realize I'm reposting this but the bug reappeared and I was able to reproduce it now.

*IF BUG, INCLUDE THIS PART:*

When attempting to use IUIVisualizerService to launch a radwindow the following error occurs:

```
00:17:01:840 => [DEBUG] [Catel.MVVM.TaskCommand`3] [1] Executing task command
WPFApplication1.exe Error: 0 : 00:17:01:845 => [ERROR] [Catel.MVVM.TaskCommand`3] [1] Task ended with exception | [ArgumentException] System.ArgumentException: Object of type 'System.EventHandler' cannot be converted to type 'System.EventHandler`1[Telerik.Windows.Controls.WindowClosedEventArgs]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Catel.Services.UIVisualizerService.HandleCloseSubscription(Object window, Object data, EventHandler`1 completedProc, Boolean isModal) in C:\CI_WS\Ws\105284\Source\Catel\src\Catel.MVVM\Catel.MVVM.Shared\Services\UIVisualizerService.wpf.cs:line 141
   at Catel.Services.UIVisualizerService.ShowWindowAsync(FrameworkElement window, Object data, Boolean showModal) in C:\CI_WS\Ws\105284\Source\Catel\src\Catel.MVVM\Catel.MVVM.Shared\Services\UIVisualizerService.wpf.cs:line 155
   at Catel.Services.UIVisualizerService.<ShowAsync>d__13.MoveNext() in C:\CI_WS\Ws\105284\Source\Catel\src\Catel.MVVM
\Catel.MVVM.Shared\Services\UIVisualizerService.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Catel.Services.UIVisualizerService.<ShowAsync>d__12.MoveNext() in C:\CI_WS\Ws\105284\Source\Catel\src\Catel.MVVM\Catel.MVVM.Shared\Services\UIVisualizerService.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WPFApplication1.ViewModels.RibbonViewModel.<LaunchWindowCommand>d__2.MoveNext() in D:\Users\hayth\Documents\Visual Studio 2015\Projects\WPFApplication1\WPFApplication1\ViewModels\RibbonViewModel.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Catel.MVVM.TaskCommand`3.<Execute>d__37.MoveNext() in C:\CI_WS\Ws\105284\Source\Catel\src\Catel.MVVM\Catel.MVVM.Shared\MVVM\Commands\TaskCommand.cs:line 269
An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.dll
Object of type 'System.EventHandler' cannot be converted to type 'System.EventHandler`1[Telerik.Windows.Controls.WindowClosedEventArgs]'.
```

### Steps to reproduce

1. Launch the application
2. Click on the button in the ribbon that will launch the model window

Platform:
.NET version: 4.6.1

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?
I've attached a repro of the problem

[Repro.zip](https://github.com/Catel/Catel/files/1400840/Repro.zip)

**Comment by GeertvanHorrik** [comment]
We need to check the event handler used by Telerik for the close event.

**Comment by halbustami** [comment]
Geert,

I took the liberty to look into this a little.  Under the "HandleCloseSubscription(object window, object data, EventHandler<UICompletedEventArgs> completedProc, bool isModal)" method in the "UIVisualizerService" I changed the event handler to a generic to "EventHandler<WindowClosedEventArgs> eventHandler = null;" just to test it out as you can see in the attached screenshot and it looks like this would work.  
![capture](https://user-images.githubusercontent.com/7476284/35203697-234fcf40-feef-11e7-9f4c-7b3e37d5d303.PNG)

However, this is not really a practical solution. Do you think that it would be worth passing those event arguments as optional parameters in the ShowAsync methods and modify the  HandleCloseSubscription to handle those if not null? I have produced a better Repro if you'd like to see it.

**Comment by GeertvanHorrik** [comment]
Thanks for the investigation. I don't believe we use the event args at all in that method. In that case it should be irrelevant, but I wasn't aware you could simply cast an `EventHandler<T>` to `EventHandler`. Does using `EventHandler` work in both Telerik and regular windows?

**Comment by halbustami** [comment]
I did some further fiddling with this. You are correct, you can't just simply cast to between `EventHandler` and` EventHander<T>` ; will have to get some reflection involved. Only practical solution I can think of right now is to just create a new class and inherit from` IUIVisualizerService ` and then override the `HandleCloseSubscription` method. I did some initial testing and it's working. If this proves to be practical then documenting the way to do it in your Catel documentation for Radwindows would be the way to go. I'll keep you posted.

**Comment by advapiIT** [comment]
@halbustami since you're using Telerik can we share thoughts? maybe on gitter? (I'll delete this post after your answer

**Comment by halbustami** [comment]
K I'm on gitter. Be warned however, I am not a developer. I am an engineer who help write applications and mostly code as a hobby.

**Comment by halbustami** [comment]
@GeertvanHorrik , Like I said above I think the simplest solution is just to update the documentation for Radwindow  mentioned in [http://docs.catelproject.com/5.2/catel-mvvm/views/xaml/external-controls/using-custom-window/]() and show how to override the `HandleCloseSubscription` method. If not, then we would need to come up with some logic to cast the `EventHandler `to whatever `EventHander<T>` a window would use. What do you think? If you agree then this could be closed. I could help with the documentation if you don't have time.

**Comment by GeertvanHorrik** [comment]
@halbustami I think you are right, we shouldn't be modifying the code just because of some 3rd party fx. Would love to see the docs updated with a PR, thanks in advance!
