### ISSUE TITLE
Serializer trapped in endless loop when deserializing

### ISSUE THREAD

**Issue by Mazzelfassel** [Catel/Catel#2018]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

ISerializer / XmlSerializer

## Version of Library

5.12.22

## Version of OS(s) listed above with issue

Win 10

## Steps to Reproduce
1. Create Class1 inheriting from ModelBase with no default constructor (for example using dependency injection)
2. Create Class2 inheriting from ModelBase with a catel propety of type Class1
3. Serialize  Class2
4. Deserialize the Class2

## Expected Behavior

Deserialization finished either successfull or throws an exception (don't know what would be the correct behavior)
If possible inject the corresponding types at construction?

## Actual Behavior

Deserialization never finishes and loops endlessly throwing the same exception into the console over and over.
```
13:30:36:797 => [DEBUG] [Catel.Runtime.Serialization.Xml.XmlSerializer] [16] Failed to deserialize 'Tests.TestClass2.TestClass' | [InvalidDataContractException] System.Runtime.Serialization.InvalidDataContractException: IXmlSerializable Type 'Tests.TestClass1' must have default constructor.
   at System.Runtime.Serialization.XmlDataContract.GetConstructor()
   at System.Runtime.Serialization.XmlDataContract.RequiresMemberAccessForCreate(SecurityException securityException)
   at System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate()
   at System.Runtime.Serialization.XmlDataContract.get_CreateXmlSerializableDelegate()
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadIXmlSerializable(XmlSerializableReader xmlSerializableReader, XmlReaderDelegator xmlReader, XmlDataContract xmlDataContract, Boolean isMemberType)
   at System.Runtime.Serialization.XmlDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlReader reader, Boolean verifyObjectName)
   at Catel.Runtime.Serialization.Xml.XmlSerializer.ReadXmlObject(ISerializationContext`1 context, XmlReader xmlReader, DataContractSerializer serializer, String namespacePrefix, String xmlName, Type modelType)
   at Catel.Runtime.Serialization.Xml.XmlSerializer.GetObjectFromXmlElement(ISerializationContext`1 context, MemberValue memberValue, Type modelType)
   at Catel.Runtime.Serialization.Xml.XmlSerializer.DeserializeMember(ISerializationContext`1 context, MemberValue memberValue)
```
Classes used to reproduce the error:
```csharp
public class TestClass1 : ModelBase
{
    private readonly IUIVisualizerService _uiVisualizerService;

    public TestClass1(IUIVisualizerService uiVisualizerService)
    {
        _uiVisualizerService = uiVisualizerService;
    }

    public static readonly PropertyData Value1Property = RegisterProperty(nameof(Value1), typeof(int), 5);
    public int Value1
    {
        get => GetValue<int>(Value1Property);
        set => SetValue(Value1Property, value);
    }
}

public class TestClass2 : ModelBase
{
    public TestClass2() { }

    public static readonly PropertyData TestClassProperty = RegisterProperty(nameof(TestClass), typeof(TestClass1), null);
    public TestClass1 TestClass
    {
        get => GetValue<TestClass1>(TestClassProperty);
        set => SetValue(TestClassProperty, value);
    }

    public static readonly PropertyData StringValueProperty = RegisterProperty(nameof(StringValue), typeof(string), "Test");
    public string StringValue
    {
        get => GetValue<string>(StringValueProperty);
        set => SetValue(StringValueProperty, value);
    }
}
```

**Comment by GeertvanHorrik** [comment]
I think by default, the xml serializable objects must implement an empty (default) ctor. I think we can implement something that uses the ITypeFactory to create the type, but would need a unit test. We will also only fix this on Catel 6 (.net 6) since we don't want to put any more effort into Catel 5 unless we are hit by a blocker ourselves (we are actively migrating all other projects to Catel 6 alpha, once they work we can release as stable).

**Comment by Mazzelfassel** [comment]
I think even if it is not possible to construct them using ITypeFactory the serializer should at least throw an exception to prevent the program from freezing due to the endless loop it causes. I'm unable to further investigate this issue due to debug symbols of catel not working in my projects for some reason and thus preventing me from stepping through the code.
Regardless I'm looking forward to version 6 and will investigate this again if the problem persists.

**Comment by bluejack2000** [comment]
I have just run into the exact same issue. Code was freezing on Deserialize. Only with debugging deep into the library code I found that it repeatedly threw an InvalidDataContractException which was catched in `XmlSerializer.DeserializeMember` and just [logged](https://github.com/Catel/Catel/blob/021b606869b0576771c0e61d9bca462df56aa9d8/src/Catel.Core/Runtime/Serialization/XmlSerialization/XmlSerializer.cs#L577). The calling code could not proceed to the next element and looped over the same element [over and over](https://github.com/Catel/Catel/blob/021b606869b0576771c0e61d9bca462df56aa9d8/src/Catel.Core/Runtime/Serialization/XmlSerialization/XmlSerializer.cs#L488).

Correct behavior would here to stop deserialization with an exception instead of ignoring the problem. Reason was a missing default constructor of a property of the deserialized type which was not communicated to the developer.

**Comment by GeertvanHorrik** [comment]
Is this in v5 or v6?

**Comment by bluejack2000** [comment]
> Is this in v5 or v6?

5.12.22 for me.

**Comment by GeertvanHorrik** [comment]
Is it reproducable in v6? I am not too happy to hotfix the v5 branch, prefer the right way forward.

**Comment by bluejack2000** [comment]
A possible hotfix would be to just rethrow the `InvalidDataContractException` instead of logging. I would have to try v6 but from looking at the [v6 code](https://github.com/Catel/Catel/blob/64100dcdd3ad475b8684795c0b1aa83e2582a3ef/src/Catel.Core/Runtime/Serialization/XmlSerialization/XmlSerializer.cs#L603) it will behave the same. I guess there is a missing unit test for that case.

**Comment by GeertvanHorrik** [comment]
Sorry for the late reply, this one got buried in my inbox. Would you be interested in doing a PR that creates a unit test to repro this? In that case, we can consider adding this.

**Comment by GeertvanHorrik** [comment]
Closing as won't fix since the serialization engine is removed in Catel 7
